### ISSUE TITLE
Replace cmocean with ColorShemes.jl

### ISSUE THREAD

**Issue by Balinus** [Zeitsperre/ClimateMaps.jl#1]
ColorSchemes.jl would replace the cmocean python dep. And also provide an exhaustive list of colorscales.

**Comment by Zeitsperre** [comment]
I was actually thinking of using the other suggested library, [PerceptualColourMaps](https://github.com/peterkovesi/PerceptualColourMaps.jl) as it is better at differentiating colour at smaller degrees and includes more standardized schemes. For more info: https://arxiv.org/abs/1509.03700

**Comment by Balinus** [comment]
Nice find. Haven't heard of it.
