### ISSUE TITLE
Switching to Cartopy - Deprecate Basemap

### ISSUE THREAD

**Issue by Balinus** [Zeitsperre/ClimateMaps.jl#2]
Basemap will soon be no longer supported. And it's also a mess with Python 3.6+. Once ClimateTools is splitted (ClimateTools/ClimateMaps), I strongly suggest we port the code to use Cartopy before adding any new features in ClimateMaps.

Better yet would be to develop a strong support for PlotlyJS.jl. Maps are awesome, but this would involve unloading the projection part to GDAL.jl and then plot on PlotlyJS.jl.

**Comment by Zeitsperre** [comment]
Yeah, I noticed that when trying to build a clean version of ClimateTools with Py37. Will look into this.

**Comment by Balinus** [comment]
Yes, the easiest way to build ClimateTools is to create a virtual python env, install the appropriate packages. 

conda create -name python_julia python=3.4
etc...

Then, in Julia, build PyCall with the following commands:
```julia
ENV["PYTHON"]="/path/to/virtualenv"
Pkg.build("PyCall")
```

**Comment by Balinus** [comment]
I played a little bit with cartopy and right now I'm far from having success. Might be caused by local configurations though.
