### ISSUE TITLE
Consider GMT.jl as engine behind mapping library

### ISSUE THREAD

**Issue by Zeitsperre** [Zeitsperre/ClimateMaps.jl#3]
see: https://genericmappingtools.github.io/GMT.jl/latest/usage/

This library has a lot of promise. Worth investigating further.

**Comment by Balinus** [comment]
Indeed. We would need proper wrappers though as the barebone GMT.jl commands are quite obscure for end-users. But I agree that would be a really nice way to leave Python deps behind.

Another alternative would be to use GDAL.jl + PlotlyJS.jl.

**Comment by Zeitsperre** [comment]
GDAL is fairly intuitive. I'm currently building some barebones wrappers for GDAL in another project. Also worth consideration.
