### ISSUE TITLE
Define a few more default projections

### ISSUE THREAD

**Issue by Zeitsperre** [Zeitsperre/ClimateMaps.jl#5]
This can probably be combined with #3 when we decide to work on the projection definition wrappers, but it would be good to make it more intuitive to pick and choose different projections by default.

If it's a simple matter as translating the GMT.jl definitions ([written here](http://gmt.soest.hawaii.edu/doc/latest/basemap.html)) to something a little more intuitive, that can be done fairly easily.

**Comment by Balinus** [comment]
Totally agree on more default projections. Also, a more generic approach I'd say that the one currently implemented so that end-users can easily plot their own results without relying on hardcoded regions/projections.
